{% set name = "arcos-gui" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arcos_gui-{{ version }}.tar.gz
  sha256: 4c6e5664621aeb630961a6599763b98c72c31e72577eedcb22dd5699270d9197

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - arcos4py >=0.2.2
    - matplotlib-base >=3.3.4
    - napari >=0.4.15
    - numpy >=1.21.5
    - pandas >=1.3.5
    - python >=3.8
    - scikit-image >=0.18.1
    - scipy >=1.7.3
    - pyarrow >=11.0.0
    - qtpy

test:
  imports:
    - arcos_gui
    - arcos_gui.widgets
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://github.com/bgraedel/arcos-gui
  summary: A napari plugin to detect and visualize collective signaling events
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgraedel
    - goanpeca
    - jaimergp
